platform=android


deviceName=Android Emulator
platformVersion=17
udid=

app=
appPackage=com.saucelabs.mydemoapp.android
appActivity=com.saucelabs.mydemoapp.android.view.activities.SplashActivity
appWaitActivity=com.saucelabs.mydemoapp.android.view.activities.MainActivity
appWaitDuration=30000

noReset=false
fullReset=false

timeout.default=15
